name: Valdemar Lozada
author: "Valdemar Lozada"
description: Administrador de sistemas GNU/Linux, entusiasta del desarrollo web y defensor de la privacidad cibernética.
author_email: contacto@vlozada.com

twitter_username: vlozadaDev
github_username: vlozadadotcom

paginate: 5
paginate_path: "/page:num/"
permalink: /:title/
baseurl: ""
url: https://vlozada.com
timezone: "America/Lima"
highlighter: "rouge"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - CNAME
  - .gitignore
  - README.md
  - Gemfile
  - Gemfile.lock

webmentions:
  username: vlozada.com
  # Use my own cache folder
  cache_folder: .cache
  # skip bad URLs for 5 days
  cache_bad_uris_for: 5
  # I moved to www and then to https, so…
  legacy_domains:
    - https://vlozada.com
    - https://www.vlozada.com
