name: lordvalor
author: "@lordvalor"
description: Linux system administrator and web development enthusiast, Minimalist, Open Source activist. Debian GNU / Linux user.
author_email: vlozada@protonmail.com

twitter_username: lordvalor
github_username: lordvalor

paginate: 5
paginate_path: "/page:num/"
permalink: /:title/
baseurl: ""
url: https://lordvalor.github.com
timezone: 'America/Lima'
highlighter: 'rouge'
plugins:
- jekyll-feed
- jekyll-paginate
- jekyll-sitemap
- jekyll-seo-tag

exclude:
- CNAME
- .gitignore
- README.md
- Gemfile
- Gemfile.lock
