name: Valdemar Lozada
author: "Valdemar Lozada"
description: Administrador de sistemas GNU/Linux, entusiasta del desarrollo web y defensor de la privacidad cibernética.
author_email: valdemar@vlozada.com
baseurl: ""
url: https://vlozada.com

social: 
  - github_username: lordvalor

paginate: 5
paginate_path: "/page:num/"
permalink: /:title.html


timezone: "America/Lima"
highlighter: "rouge"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - CNAME
  - .gitignore
  - README.md
  - Gemfile
  - Gemfile.lock
  

webmentions:
  username: vlozada.com
  # Use my own cache folder
  cache_folder: .cache
  # skip bad URLs for 5 days
  cache_bad_uris_for: 5
  # I moved to www and then to https, so…
  legacy_domains:
    - https://vlozada.com
    - https://www.vlozada.com
