# Site settings
title: Lordvalor
email: hola@lordvalor.com.ve
description: "Blog de Valdear Lozada."
baseurl: ""
url: "http://www.Lordvalor.com.ve"
twitter_username: Lordvalor
github_username:  Lordvalor

# Build settings
markdown: kramdown
permalink: pretty
