title: "@lordvalor"
email: vlozada@protonmail.com
name: "Valdemar Lozada"
author: 'Valdemar Lozada'
permalink: /:title
baseurl: ""
url: "https://lordvalor.com"
description: 'blog personal de Valdemar Lozada'

twitter_username: lordvalor
github_username: lordvalor

# Format
markdown: kramdown
timezone: 'America/Lima'
highlighter: 'rouge'
plugins:
  - jekyll-feed
