name: Valdemar Lozada
author: "Valdemar Lozada"
description: Administrador de Sistemas GNU/Linux, Minimalist, Desarrollo web.
author_email: contacto@vlozada.com

twitter_username: vlozadaDev
github_username: vlozadadotcom

paginate: 5
paginate_path: "/page:num/"
permalink: /:title/
baseurl: ""
url: https://vlozada.com
timezone: "America/Lima"
highlighter: "rouge"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - CNAME
  - .gitignore
  - README.md
  - Gemfile
  - Gemfile.lock
