---
layout: base
title: 'VALDEMAR LOZADA'
name: "Valdemar Lozada"
author: 'Valdemar Lozada'
permalink: /:title
baseurl: ""
slug: home
description: 'web blog personal'

twitter: lordvalor
github: lordvalor

# Format
markdown: 'kramdown'
timezone: 'America/Lima'
highlighter: 'rouge'
---
