name: lordvalor@blog:~$
author: "@lordvalor"
description: Systems Administrator, Web development enthusiast, Minimalist, Open Source activist and free software. User of Debian GNU / Linux.
author_email: vlozada@protonmail.com

twitter_username: lordvalor
github_username: lordvalor

paginate: 5
paginate_path: "/page:num/"
permalink: /:title/
baseurl: ""
url: https://lordvalor.com
comments: true
timezone: 'America/Lima'
highlighter: 'rouge'
plugins:
- jekyll-feed
- jekyll-paginate
- jekyll-sitemap
- jekyll-seo-tag

generator: 'Jekyll - Github Pages'
exclude:
- CNAME
- .gitignore
- README.md
- Gemfile
- Gemfile.lock